apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      steamscraper.io/name: web-server
  template:
    metadata:
      labels:
        steamscraper.io/name: web-server
    spec:
      containers:
      - name: web-server
        image: {{.Values.ecr}}-frontend:{{.Values.tag}}
        volumeMounts:
        - name: certs
          mountPath: "/etc/ssl/certs"
          readOnly: true
        ports:
        - containerPort: 443
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
      volumes:
      - name: certs
        secret:
          secretName: tls-cert
      nodeSelector:
        group: frontend-group
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: frontend
spec:
  selector:
    steamscraper.io/name: web-server
  ports:
    - port: 443
  type: LoadBalancer # if you want your service to be accessible from outside the Kubernetes cluster