apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      steamscraper.io/name: compute
  template:
    metadata:
      labels:
        steamscraper.io/name: compute
    spec:
      containers:
      - name: compute
        ports:
        - containerPort: 5000 
        image: {{.Values.ecr}}-backend:{{.Values.tag}}
        env:
        - name: REDIS_HOST
          value: "redis.default.svc.cluster.local"  
        - name: REDIS_PORT
          value: "6379"
        - name: BACKEND_CG
          value: "BACKEND_CG"
        resources:
          limits:
            cpu: "0.5"
            memory: "384Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
      nodeSelector:
        group: backend-group
