apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      steamscraper.io/name: auth
  template:
    metadata:
      labels:
        steamscraper.io/name: auth
    spec:
      containers:
      - name: auth
        image: {{.Values.ecr}}-auth:{{.Values.tag}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        volumeMounts:
          - name: certs
            mountPath: "/etc/ssl/certs/"
            readOnly: true
        resources:
          limits:
            cpu: "0.5"
            memory: "384Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4000"
        - name: CORS_ORIGIN
          value: "https://steamscraper.io"
        - name: CERT_PATH
          value: "/etc/ssl/certs/steamscraper.io.crt"
        - name: CERTKEY_PATH
          value: "/etc/ssl/certs/steamscraper.io.key"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
      nodeSelector:
        group: backend-group
      imagePullSecrets:
        - name: regcred

      volumes:
      - name: certs
        secret:
          secretName: tls-cert
          items: 
            - key: tls.crt
              path: steamscraper.io.crt
            - key: tls.key
              path: steamscraper.io.key
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    steamscraper.io/name: auth
  ports:
    - port: 443
      targetPort: 4000
