apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations: 
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/default-backend: "webserver"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - steamscraper.io
    secretName: tls-cert
  rules:
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: webserver
            port:
              number: 80      
      - path: /api/auth/(.*)
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 443
      - path: /api/steam/(.*)
        pathType: Prefix
        backend:
          service:
            name: steamapi
            port:
              number: 443
