apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-server
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      steamscraper.io/name: redis
  template:
    metadata:
      labels:
        steamscraper.io/name: redis
    spec:
      containers:
      - name: redis
        image: {{.Values.ecr}}-redis:{{.Values.tag}}
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.5"
            memory: "384Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
      nodeSelector:
        group: database-cache-group
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    steamscraper.io/name: redis
  ports:
    - name: redis
      port: 6379