apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: steamapi-network-policy
spec:
  podSelector:
    matchLabels:
      steamscraper.io/name: steamapi
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
    - podSelector: {}
  egress:
  - {}