apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: steamapi-statefulset
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      steamscraper.io/name: steamapi
  template:
    metadata:
      labels:
        steamscraper.io/name: steamapi
    spec:
      containers:
      - name: steamapi
        ports:
        - containerPort: 443
        image: $(ECR_URL)-steamapi:latest
        env:
        - name: ECR_URL
          valueFrom: 
            secretKeyRef:
              name: ecr
              key: ECR_URL
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: STEAMAPI_CG
          value: STEAMAPI_CG
        - name: REDIS_REQUEST_TIMEOUT
          value: 3000
        - name: REDIS_RESPONSE_TIMEOUT
          value: 3000
        volumeMounts:
        - name: certs
          mountPath: "/etc/ssl/certs"
          readOnly: true

      volumes:
      - name: certs
        secret:
          secretName: tls-cert

      nodeSelector:
        group: backend-group

---
apiVersion: v1
kind: Service
metadata:
  name: steamapi
  namespace: backend
spec:
  selector:
    matchLabels:
      steamscraper.io/name: steamapi
  ports:
    - port: 443
  type: LoadBalancer
  