name: CI/CD pipeline
on: workflow_dispatch
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
env:
    AWS_REGION: us-east-1
    ECR_REPOSITORY: steamscraper
    ECR_PUBLIC_URI: public.ecr.aws/t4o5y2a8/steamscraper
    EKS_CLUSTER: steamscraper-eks

jobs:
    
    build_publish:
        # needs: Testing
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v4  

            - name: Configure AWS credentials from the OIDC role
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{secrets.AWS_ROLE_ARN}}
                aws-region: ${{env.AWS_REGION}}
                role-session-name: steamscraper-cicd
                
            - name: Build & Upload backend server image to ECR
              uses: appleboy/docker-ecr-action@master
              with:
                  access_key: ${{ env.AWS_ACCESS_KEY_ID }}
                  secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  registry: ${{ env.ECR_PUBLIC_URI }}
                  repo: ${{ env.ECR_REPOSITORY }}
                  region: ${{ env.AWS_REGION }}
                  tags: latest,${{ github.run_number }}
                  daemon_off: false
                  dockerfile: ./api/Dockerfile
                  context: ./

            - name: Build & Upload Steam API proxy image to ECR
              uses: appleboy/docker-ecr-action@master
              with:
                  access_key: ${{ env.AWS_ACCESS_KEY_ID }}
                  secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  registry: ${{ env.ECR_PUBLIC_URI }}
                  repo: ${{ env.ECR_REPOSITORY }}
                  region: ${{ env.AWS_REGION }}
                  tags: latest,${{ github.run_number }}
                  daemon_off: false
                  dockerfile: ./steamapi/Dockerfile
                  context: ./

            - name: Build & Upload web server image to ECR
              uses: appleboy/docker-ecr-action@master
              with:
                  access_key: ${{ env.AWS_ACCESS_KEY_ID }}
                  secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  registry: ${{ env.ECR_PUBLIC_URI }}
                  repo: ${{ env.ECR_REPOSITORY }}
                  region: ${{ env.AWS_REGION }}
                  tags: latest,${{ github.run_number }}
                  daemon_off: false
                  dockerfile: ./client/Dockerfile
                  context: ./
            
            - name: Build & Upload auth server image to ECR
              uses: appleboy/docker-ecr-action@master
              with:
                  access_key: ${{ env.AWS_ACCESS_KEY_ID }}
                  secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  registry: ${{ env.ECR_PUBLIC_URI }}
                  repo: ${{ env.ECR_REPOSITORY }}
                  region: ${{ env.AWS_REGION }}
                  tags: latest,${{ github.run_number }}
                  daemon_off: false
                  dockerfile: ./auth/Dockerfile
                  context: ./

            -   name: Build & Upload Redis server image to ECR
                uses: appleboy/docker-ecr-action@master
                with:
                  access_key: ${{ env.AWS_ACCESS_KEY_ID }}
                  secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  registry: ${{ env.ECR_PUBLIC_URI }}
                  repo: ${{ env.ECR_REPOSITORY }}
                  region: ${{ env.AWS_REGION }}
                  tags: latest,${{ github.run_number }}
                  daemon_off: false
                  dockerfile: ./redis/Dockerfile
                  context: ./
    # Testing:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Code checkout
    #         uses: actions/checkout@v4
