name: Remove all Kubernetes resources
on: workflow_dispatch
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: steamscraper
  EKS_CLUSTER: steamscraper-eks
  
jobs:
  undeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4  

      - name: Configure AWS credentials from the OIDC role
        id: aws-configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{env.AWS_REGION}}
          role-session-name: steamscraper-undeploy
          output-credentials: true

      - name: Update kubeconfig file
        run: aws eks update-kubeconfig --name ${{env.EKS_CLUSTER}} --region ${{env.AWS_REGION}}

      - name: Login to ECR
        run: aws ecr get-login-password --region ${{env.AWS_REGION}} | docker login --username AWS --password-stdin ${{ steps.aws-configuration.outputs.aws-account-id }}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com
      
      - name: Uninstall Helm charts
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.10
        with:
          aws-access-key-id: ${{ steps.aws-configuration.outputs.aws-access-key-id }}
          aws-secret-access-key: ${{ steps.aws-configuration.outputs.aws-secret-access-key }}
          aws-region: ${{ env.AWS_REGION }}
          cluster-name: ${{ env.EKS_CLUSTER }}
          action: uninstall
          name: steamscraper-stack
          create-namespace: false